info:
  name: 服务提供者(异步方式)
  version: 0.0.1

server: 
  port: 6081

management:
  security:
    enabled: false

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: topic-01
          binder: rabbit_default
      binders:
        rabbit_default:
          type: rabbit
          environment:
            spring: 
              rabbitmq:
                host: 192.168.123.132
                port: 5672
                username: user
                password: user123
                virtual-host: /async_provider01

logging:
  level:
    root: info
    com.yanshaohui.springcloud: trace